### ISSUE TITLE
license/redistribution

### ISSUE THREAD

**Issue by doctorcolossus** [Ikhyeon-Cho/urban-traversability-dataset#2]
Hello!

What is the license of this dataset? Is redistribution okay?

I am compiling a torrent of datasets relevant to traversability estimation.
May I include this urban-traversability-dataset, with attribution and a link to this repo?
If so, which license to include, if any?
Thanks!

**Comment by Ikhyeon-Cho** [comment]
@doctorcolossus  Hi, thanks for your interest in our dataset!

The urban-traversability-dataset is licensed under the Creative Commons Attribution-NonCommercial 4.0 International License (CC BY-NC 4.0). Redistribution is permitted for academic and non-commercial research purposes, as long as proper attribution is provided and a link to this repository is included.

If you’d like to use the dataset for commercial purposes, please contact us directly for permission.

Thank you for including our dataset in your compilation, and we appreciate your support in advancing research! If you have further questions, feel free to ask.
